---
root: true
env:
  browser: true
  "es6": true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures: { }
extends:
  - airbnb
  - prettier
rules:
  no-underscore-dangle: [ "error", { "allowAfterThis": true } ]